### PR TITLE
Xcode 7.3 optional support

### LINKED ISSUE #54: Under Xcode 7.3 NSDate? are interpreted as Int? by the Compiler causing NSDate? properties to not be set
The compiler appears to interpret NSDate? as Int? and thus setting NSDate? properties fails.

```
public func <-- <T>(inout property: T?, value: AnyObject?) -> T? {
  var newValue: T?
  ""
  if let unwrappedValue: AnyObject = convertToNilIfNull(value) {
    // We unwrapped the given value successfully, try to convert.
    if let convertedValue = unwrappedValue as? T {
      // Convert by just type-casting.
      newValue = convertedValue
    } else {
      // Convert by processing the value first.
      switch property {
      case is Int?:
        if unwrappedValue is String {
          if let intValue = Int("\(unwrappedValue)") {
            newValue = intValue as? T
          }
        }
      case is NSURL?:
        newValue = NSURL(string: "\(unwrappedValue)") as? T
      case is NSDate?:
        if let timestamp = unwrappedValue as? Int {
          newValue = NSDate(timeIntervalSince1970: Double(timestamp)) as? T
        } else if let timestamp = unwrappedValue as? Double {
          newValue = NSDate(timeIntervalSince1970: timestamp) as? T
        } else if let timestamp = unwrappedValue as? NSNumber {
          newValue = NSDate(timeIntervalSince1970: timestamp.doubleValue) as? T
        }
      default:
        break
      }
    }
  }
  property = newValue
  return property
}
```

Instead of reaching ```case is NSDate?:```, execution inside the switch enters ```case is Int?:```

This problem occurs in Xcode 7.3.

### PR DESCRIPTION
**Pull request by jondwillis**
change order of switch statement so that `Int?` is considered last

Fixes #54 

---
This change is [Reviewable](https://reviewable.io/reviews/isair/jsonhelper/56)

### CODE REVIEW

**Comment by jondwillis** [comment]
https://github.com/isair/JSONHelper/issues/54

**Comment by isair** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/isair/jsonhelper/56)*

**Comment by isair** [comment]
Thanks @jondwillis!

**Comment by ldi13** [comment]
Hello,

I also use JSONHelper as a parser into my project.
And for the last version of Xcode 7.3 / Swift 2.2, I noticed that optionals are definitely not handled correctly when "is" statement tries to reveal the value type of the property tested. It's not due to JSONHelper, but I think it's clearly a Swift issue.

Here is the stackoverflow ticket opened regarding this subject:
http://stackoverflow.com/questions/36160934/type-of-optionals-cannot-be-inferred-correctly-in-swift-2-2

Here is also the ticket we opened on Swift portal: https://bugs.swift.org/browse/SR-1024

I don't think that moving the switch statement block for Int? case at last position fixes the parsing issue, because I think it will enter directly after into NSURL? switch case but I'll try.

If you have anything new on that topic, please share :)

All the best,

Lorenzo.

**Comment by ldi13** [comment]
Hello,

I just checked and this modification into JSONHelper doesn't fix the issue, if you have any optional value as parameter, the "case is NSURL?" statement will be executed every time, whatever the type (Int?, String?) defined for the pointer property parameter.

**Comment by isair** [comment]
@ldi13 Thanks for the links. This issue also breaks some of my own apps, so I'll try to release JSONHelper 2.0.0 in the following days which doesn't have this issue due to how differently it handles conversions. Stay tuned. :)

**Pull request merged**
